## TASK 1

In [15]:
import pandas as pd
import numpy as np

# Read dataset
df = pd.read_csv("cosmetics.csv", engine="python", on_bad_lines="skip")# only one bad line that is 1338th row
# Display 5 random rows
df.sample(5)

,Label,Brand,Name,Price,Rank,Ingredients,Combination,Dry,Normal,Oily,Sensitive
1037,Face Mask,ORIGINS,RitualiTea™ Matcha Madness™ Revitalizing Powde...,36,3.8,"Avena Sativa (Oat) Kernel Meal, Sodium Bicarbo...",1,1,1,1,0
1253,Eye cream,DIOR,Capture Totale 360 Light-Up Open-Up Replenishi...,110,4.1,Visit the Dior boutique,0,0,0,0,0
898,Face Mask,DR. JART+,Shake & Shot™ Rubber Masks,12,4.1,-Vitamin C (Ascorbic Acid): Brightens the look...,1,1,1,1,1
1067,Face Mask,ORIGINS,Flower Fusion™ Lavender Soothing Sheet Mask,7,4.3,"Water, Butylene Glycol, Bis-Peg-18 Methyl Ethe...",1,1,1,1,1
437,Cleanser,CLINIQUE,Rinse-Off Eye Makeup Solvent,19,4.3,"Water , Peg-32 , Butylene Glycol , Disodium Co...",0,0,0,0,0

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1337 entries, 0 to 1336
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Label        1337 non-null   str
 1   Brand        1337 non-null   str
 2   Name         1337 non-null   str
 3   Price        1337 non-null   int64
 4   Rank         1337 non-null   float64
 5   Ingredients  1337 non-null   str
 6   Combination  1337 non-null   int64
 7   Dry          1337 non-null   int64
 8   Normal       1337 non-null   int64
 9   Oily         1337 non-null   int64
 10  Sensitive    1337 non-null   int64
dtypes: float64(1), int64(6), str(4)
memory usage: 1.1 MB

In [13]:
df.columns

Index(['Label', 'Brand', 'Name', 'Price', 'Rank', 'Ingredients', 'Combination',
       'Dry', 'Normal', 'Oily', 'Sensitive'],
      dtype='str')

In [14]:
df["Label"].value_counts()

Label
Moisturizer    298
Cleanser       281
Face Mask      266
Treatment      248
Eye cream      209
Sun protect     35
Name: count, dtype: int64

In [16]:
!pip freeze > requirements.txt

WARNING: Ignoring invalid distribution ~atplotlib (D:\Installation\Lib\site-packages)

## TASK 2

In [19]:
# Keep only moisturizers
moisturizers = df[df["Label"] == "Moisturizer"]

# View first 5 rows
moisturizers.head()

,Label,Brand,Name,Price,Rank,Ingredients,Combination,Dry,Normal,Oily,Sensitive
0,Moisturizer,LA MER,Crème de la Mer,175,4.1,"Algae (Seaweed) Extract, Mineral Oil, Petrolat...",1,1,1,1,1
1,Moisturizer,SK-II,Facial Treatment Essence,179,4.1,"Galactomyces Ferment Filtrate (Pitera), Butyle...",1,1,1,1,1
2,Moisturizer,DRUNK ELEPHANT,Protini™ Polypeptide Cream,68,4.4,"Water, Dicaprylyl Carbonate, Glycerin, Ceteary...",1,1,1,1,0
3,Moisturizer,LA MER,The Moisturizing Soft Cream,175,3.8,"Algae (Seaweed) Extract, Cyclopentasiloxane, P...",1,1,1,1,1
4,Moisturizer,IT COSMETICS,Your Skin But Better™ CC+™ Cream with SPF 50+,38,4.1,"Water, Snail Secretion Filtrate, Phenyl Trimet...",1,1,1,1,1

In [23]:
# Keep moisturizers suitable for dry skin
moisturizers_dry = moisturizers[moisturizers["Dry"] == 1]

# Reset index
moisturizers_dry = moisturizers_dry.reset_index(drop=True)

# Check size
moisturizers_dry

,Label,Brand,Name,Price,Rank,Ingredients,Combination,Dry,Normal,Oily,Sensitive
0,Moisturizer,LA MER,Crème de la Mer,175,4.1,"Algae (Seaweed) Extract, Mineral Oil, Petrolat...",1,1,1,1,1
1,Moisturizer,SK-II,Facial Treatment Essence,179,4.1,"Galactomyces Ferment Filtrate (Pitera), Butyle...",1,1,1,1,1
2,Moisturizer,DRUNK ELEPHANT,Protini™ Polypeptide Cream,68,4.4,"Water, Dicaprylyl Carbonate, Glycerin, Ceteary...",1,1,1,1,0
3,Moisturizer,LA MER,The Moisturizing Soft Cream,175,3.8,"Algae (Seaweed) Extract, Cyclopentasiloxane, P...",1,1,1,1,1
4,Moisturizer,IT COSMETICS,Your Skin But Better™ CC+™ Cream with SPF 50+,38,4.1,"Water, Snail Secretion Filtrate, Phenyl Trimet...",1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
185,Moisturizer,KIEHL'S SINCE 1851,Ultra Facial Deep Moisture Balm,29,4.7,"Water, Glycerin, Shea Butter, Glyceryl Stearat...",0,1,1,0,0
186,Moisturizer,SHISEIDO,White Lucent All Day Brightener Broad Spectrum...,62,4.6,"Water, Sd Alcohol 40-B, Dimethicone, Dipropyle...",1,1,1,0,0
187,Moisturizer,SATURDAY SKIN,Featherweight Daily Moisturizing Cream,49,4.6,"Water, Butylene Glycol, Ethylhexyl Palmitate, ...",1,1,1,1,1
188,Moisturizer,KATE SOMERVILLE,Goat Milk Moisturizing Cream,65,4.1,"Water, Ethylhexyl Palmitate, Myristyl Myristat...",1,1,1,1,1
189,Moisturizer,GO-TO,Face Hero,34,4.8,"Almond Oil, Jojoba Oil, Macadamia Oil, Brazil ...",1,1,1,1,1

In [26]:
moisturizers_dry[["Brand","Name","Price","Rank"]].head(10)

,Brand,Name,Price,Rank
0,LA MER,Crème de la Mer,175,4.1
1,SK-II,Facial Treatment Essence,179,4.1
2,DRUNK ELEPHANT,Protini™ Polypeptide Cream,68,4.4
3,LA MER,The Moisturizing Soft Cream,175,3.8
4,IT COSMETICS,Your Skin But Better™ CC+™ Cream with SPF 50+,38,4.1
5,DRUNK ELEPHANT,Lala Retro™ Whipped Cream,60,4.2
6,DRUNK ELEPHANT,Virgin Marula Luxury Facial Oil,72,4.4
7,KIEHL'S SINCE 1851,Ultra Facial Cream,29,4.4
8,KIEHL'S SINCE 1851,Midnight Recovery Concentrate,47,4.4
9,SUNDAY RILEY,Luna Sleeping Night Oil,105,4.1

## TASK 3

In [28]:
# Create a working copy
moisturizers = moisturizers_dry.copy()

In [29]:
# Convert ingredient text to lowercase as Machine learning treats different cases as different words, so we standardize everything.
moisturizers["Ingredients"] = moisturizers["Ingredients"].str.lower()

In [30]:
# Split ingredients into a list
moisturizers["Tokens"] = moisturizers["Ingredients"].str.split(", ")

In [43]:
moisturizers["Tokens"].iloc[0]

['algae (seaweed) extract',
 'mineral oil',
 'petrolatum',
 'glycerin',
 'isohexadecane',
 'microcrystalline wax',
 'lanolin alcohol',
 'citrus aurantifolia (lime) extract',
 'sesamum indicum (sesame) seed oil',
 'eucalyptus globulus (eucalyptus) leaf oil',
 'sesamum indicum (sesame) seed powder',
 'medicago sativa (alfalfa) seed powder',
 'helianthus annuus (sunflower) seedcake',
 'prunus amygdalus dulcis (sweet almond) seed meal',
 'sodium gluconate',
 'copper gluconate',
 'calcium gluconate',
 'magnesium gluconate',
 'zinc gluconate',
 'magnesium sulfate',
 'paraffin',
 'tocopheryl succinate',
 'niacin',
 'water',
 'beta-carotene',
 'decyl oleate',
 'aluminum distearate',
 'octyldodecanol',
 'citric acid',
 'cyanocobalamin',
 'magnesium stearate',
 'panthenol',
 'limonene',
 'geraniol',
 'linalool',
 'hydroxycitronellal',
 'citronellol',
 'benzyl salicylate',
 'citral',
 'sodium benzoate',
 'alcohol denat.',
 'fragrance.']

In [36]:
# #Python creates:

# Ingredient
# Index
# water 0
# glycerin 1
# aloe 2
# vitamin e 3

# This dictionary is called ingredient_idx.
# It maps every ingredient to a unique number.
    
ingredient_idx = {}
idx = 0

for ingredients in moisturizers["Tokens"]:
    for ingredient in ingredients:
        if ingredient not in ingredient_idx:
            ingredient_idx[ingredient] = idx
            idx += 1

In [37]:
print("Total unique ingredients:", len(ingredient_idx))

Total unique ingredients: 2233

In [45]:
list(ingredient_idx.items())[:30]

[('algae (seaweed) extract', 0),
 ('mineral oil', 1),
 ('petrolatum', 2),
 ('glycerin', 3),
 ('isohexadecane', 4),
 ('microcrystalline wax', 5),
 ('lanolin alcohol', 6),
 ('citrus aurantifolia (lime) extract', 7),
 ('sesamum indicum (sesame) seed oil', 8),
 ('eucalyptus globulus (eucalyptus) leaf oil', 9),
 ('sesamum indicum (sesame) seed powder', 10),
 ('medicago sativa (alfalfa) seed powder', 11),
 ('helianthus annuus (sunflower) seedcake', 12),
 ('prunus amygdalus dulcis (sweet almond) seed meal', 13),
 ('sodium gluconate', 14),
 ('copper gluconate', 15),
 ('calcium gluconate', 16),
 ('magnesium gluconate', 17),
 ('zinc gluconate', 18),
 ('magnesium sulfate', 19),
 ('paraffin', 20),
 ('tocopheryl succinate', 21),
 ('niacin', 22),
 ('water', 23),
 ('beta-carotene', 24),
 ('decyl oleate', 25),
 ('aluminum distearate', 26),
 ('octyldodecanol', 27),
 ('citric acid', 28),
 ('cyanocobalamin', 29)]